FROM node:18 as development

WORKDIR /transcendence/backend

RUN apt-get update && apt-get install --no-install-recommends -y \
    postgresql-client

COPY package*.json ./

RUN npm clean-install 

COPY . .

RUN npm run build

EXPOSE 3000

ENTRYPOINT ["sh", "entrypoint.sh"]