FROM node:18 as development

WORKDIR /transcendence

RUN apt-get update && apt-get install --no-install-recommends -y \
    postgresql-client \
    netcat

COPY package*.json ./

RUN npm clean-install

COPY . .

RUN npx prisma generate
RUN npm run build

EXPOSE 3000

ENTRYPOINT ["sh", "entrypoint.sh"]
